<?php

function internet_archive_thumb_from_file_url($url) {
  internet_archive_item_from_file_url($url);
  $pathinfo = pathinfo($url);
  $filename = $pathinfo['filename'] . '_000001.jpg';

  $link = 'http://www.archive.org/download/';
  $link .= $item .'/'. $item .'.thumbs/';
  $link .= $filename;

  return $link;
}

function internet_archive_item_from_file_url($url) {
  $urlinfo = parse_url($url);
  dsm($urlinfo);
}
