<?php
function om_volunteer_menu() {
  $items = array();
  return $items;
}

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function om_volunteer_commerce_checkout_pane_info() {
  $checkout_panes = array();
  $checkout_panes['om_volunteer_discount'] = array(
    'title' => t('Volunteer Hours Discount'),
    'page' => 'checkout',
    'locked' => TRUE,
    'file' => 'includes/om_volunteer_discount.checkout_pane.inc',
    'base' => 'om_volunteer_discount',
    'weight' => 10,
    'callbacks' => array(
      'checkout_form' => 'om_volunteer_discount_checkout_form',
      'checkout_form_submit' => 'om_volunteer_discount_checkout_form_submit'
    )
  );
  return $checkout_panes;
}
         
function om_volunteer_discount_checkout_form_submit($form, &$form_state) {
  dsm( $form_state['order']);
  $multiple = om_volunteer_get_multiple() * 100;
}

function om_volunteer_get_multiple() {
  return .1;
}
