<?php
function om_volunteer_menu() {
  $items = array();
  return $items;
}

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function om_volunteer_commerce_checkout_pane_info() {
  $checkout_panes = array();
  $checkout_panes['om_volunteer_discount'] = array(
    'title' => t('Volunteer Hours Discount'),
    'page' => 'checkout',
    'locked' => TRUE,
    'product' => FALSE,
    'file' => 'includes/om_volunteer_discount.checkout_pane.inc',
    'base' => 'om_volunteer_discount',
    'weight' => 10,
  );
  return $checkout_panes;
}

/**
 * Implements hook_commerce_line_item_type_info().
 */
function om_volunteer_commerce_line_item_type_info() {
  $line_item_types = array();
  $line_item_types['volunteer_hours'] = array(
    'type' => 'volunteer_hours',
    'name' => t('!Points', userpoints_translation()),
    'description' => t('!Points value line item.', userpoints_translation()),
    'add_form_submit_value' => t('Use !points', userpoints_translation()),
    'base' => 'volunteer_hours_line_item',
  );
  return $line_item_types;
}
