<?php

// define the source database
define("SOURCE_DATABASE", 'dom_prod');
define("CIVI_DATABASE", 'dom_civi_prod');
// All users who have signed into account after this date will be migrated.
$cutoff = new DateTime("2012-01-01");
define("USER_MIGRATION_CUTOFF",$cutoff->getTimestamp());
/**
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function om_migration_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'OM_USER' => array('class_name' => 'omUserMigration'),
      'OM_USER2' => array('class_name' => 'omUserWithProjectMigration'),
      'OM_USER3' => array('class_name' => 'omUserWithMembershipMigration'),
      'OM_USER4' => array('class_name' => 'omUserWithCertificationMigration'),
      'om_project' => array('class_name' => 'omProjectMigration'),
      'OM_SHOW' => array('class_name' => 'omShowMigration'),
    ),
  );

  return $api;
}

function om_migration_role_product_relationships() {
  return array(
    // programming membership
    1 => 5,
    // field
    3 => 6,
    // studio
    4 => 8,
    // unlimited
    5 => 9,
    // organizational
    6 => 10,
  );
}

