<?php

function commerce_registration_fixes_commerce_checkout_page_info_alter(&$checkout_pages) {
  if(!commerce_registration_fixes_is_registration_cart()) {
    unset($checkout_pages['registration']);
  }
}

function commerce_registration_fixes_is_registration_cart() {
  global $user;

  //disable notices momentarily due to unresolvable issue with commerce
  //http://drupal.org/node/1461726
  $old_error_reporting = error_reporting(error_reporting() ^ E_NOTICE);
  $current_error_reporting = error_reporting();
  error_reporting(E_ERROR | E_WARNING | E_PARSE);
  $cart = commerce_cart_order_load($user->uid);
  error_reporting($old_error_reporting);

  $registration_status = false;
  if(!empty($cart->commerce_line_items[LANGUAGE_NONE])) {
    foreach($cart->commerce_line_items[LANGUAGE_NONE] as $id => $info) {
      $line_item = commerce_line_item_load($info['line_item_id']); 
      if(commerce_registration_product_has_registration_field($line_item->commerce_product[LANGUAGE_NONE][0]['product_id'])) {
        $registration_status = true;
      }
    }
  }

  return $registration_status; 
}

function commerce_registration_fixes_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'commerce_checkout_form_registration') {
    global $user;
    $info = profile2_load_by_user($user, 'contact');
    print '<pre>';
    print_r($info);
    print '</pre>';
  }
}
