<?php

function commerce_registration_fixes_commerce_checkout_page_info_alter(&$checkout_pages) {
  if(!commerce_registration_fixes_is_registration_cart()) {
    unset($checkout_pages['registration']);
  }
}

function commerce_registration_fixes_is_registration_cart() {
  global $user;

  //disable notices momentarily due to unresolvable issue with commerce
  //http://drupal.org/node/1461726
  $old_error_reporting = error_reporting(error_reporting() ^ E_NOTICE);
  $current_error_reporting = error_reporting();
  error_reporting(E_ERROR | E_WARNING | E_PARSE);
  $cart = commerce_cart_order_load($user->uid);
  error_reporting($old_error_reporting);

  $registration_status = false;
  if(!empty($cart->commerce_line_items[LANGUAGE_NONE])) {
    foreach($cart->commerce_line_items[LANGUAGE_NONE] as $id => $info) {
      $line_item = commerce_line_item_load($info['line_item_id']); 
      if(commerce_registration_product_has_registration_field($line_item->commerce_product[LANGUAGE_NONE][0]['product_id'])) {
        $registration_status = true;
      }
    }
  }

  return $registration_status; 
}

function commerce_registration_fixes_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'commerce_checkout_form_registration') {

    $form['omp']['#after_build'] = array('commerce_registration_fixes_load_js');

    global $user;
    $contact_info = profile2_load_by_user($user, 'contact_info');
    $first_name = $contact_info->field_first_name[LANGUAGE_NONE][0]['safe_value'];
    $last_name = $contact_info->field_last_name[LANGUAGE_NONE][0]['safe_value'];
    $phone = $contact_info->field_phone_number[LANGUAGE_NONE][0]['safe_value'];
    //print '<pre>';
    //print_r($form);
    //print '</pre>';
    foreach($form['registration_information'] as $class_key => $class) {
      if(is_array($class)) {
        reset($class);
        $reg_key = key($class);
        if($reg_key) {
          if($first_name) {
            $form['registration_information'][$class_key][$reg_key]['field_first_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $first_name; 
          }
          if($last_name) {
            $form['registration_information'][$class_key][$reg_key]['field_last_name'][LANGUAGE_NONE][0]['value']['#default_value'] = $last_name; 
          }
          if($phone) {
            $form['registration_information'][$class_key][$reg_key]['field_phone_number'][LANGUAGE_NONE][0]['value']['#default_value'] = $phone; 
          }
	  if($form['registration_information'][$class_key][$reg_key]['register_for']) {
            $form['registration_information'][$class_key][$reg_key]['register_for']['#default_value'] = 'registration_registrant_type_me';
	  }
        }
      }
    }
  }
}

function commerce_registration_fixes_load_js($element) {
  drupal_add_js(drupal_get_path('module', 'commerce_registration_fixes').'/js/clearother.js');
  return $element;	
}
