<?php
/**
 * Implements hook_theme
 */
function om_jwplayer_theme($existing, $type, $theme, $path) {
  return array(
    'om_show_share_bar' => array(
      'path' => $path . '/theme',
      'template' => 'share_bar',
      'file' => 'theme.inc',
      'variables' => array(),
    )
  );
}

/**
 * Implements hook_menu
 */
function om_jwplayer_menu() {
  $items = array();
  $items['node/%node/share'] = array(
    'page callback' => 'om_jwplayer_share_show',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  return $items;
}

function om_jwplayer_share_show($node) {
 return array();
}


