<?php

function commerce_registration_fixes_commerce_checkout_page_info_alter(&$checkout_pages) {
  global $user;
  $cart = commerce_cart_order_load($user->uid);
  $registration_enabled = false;
  dsm($cart);
  foreach($cart->commerce_line_items[LANGUAGE_NONE] as $id => $info) {
    if(commerce_registration_product_has_registration_field($info->line_item_id)) {
      dsm('Commerce registration enabled for: '.$info->line_item_id);
      $registration_enabled = true;
    }
  }

  if(!$registration_enabled) {
    dsm('removing registration checkout page');
    unset($checkout_pages['registration']);
  }
}
