<?php

function commerce_registration_fixes_commerce_checkout_page_info_alter(&$checkout_pages) {
  if(!commerce_registration_fixes_is_registration_cart()) {
    unset($checkout_pages['registration']);
  }
}

function commerce_registration_fixes_is_registration_cart() {
  global $user;
  $cart = commerce_cart_order_load($user->uid);
  $registration_status = false;

  if(!empty($cart->commerce_line_items[LANGUAGE_NONE])) {
    foreach($cart->commerce_line_items[LANGUAGE_NONE] as $id => $info) {
      $line_item = commerce_line_item_load($info['line_item_id']); 
      if(commerce_registration_product_has_registration_field($line_item->commerce_product[LANGUAGE_NONE][0]['product_id'])) {
        $registration_status = true;
      }
    }
  }

  return $registration_status; 
}
