<?php


function om_admin_menu_admin_menu_output_build(&$content) {
  $paid_memberships = om_admin_menu_paid_memberships();
  $content['menu']['dashboard'] = array(
    '#title' => t('Dashboard'),
    '#access' => om_admin_menu_role_access(array('authenticated user')),
    '#href' => 'dashboard',
	);
  $content['menu']['shows'] = array(
    '#title' => t('Manage Shows'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/shows',
  );
  $content['menu']['shows']['view'] = array(
    '#title' => t('View Shows'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/shows',
  );
	$content['menu']['shows']['add'] = array(
    '#title' => t('Submit new show'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'node/add/om-show',
	);
  $content['menu']['projects'] = array(
    '#title' => t('Manage Projects'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/projects',
  );
  $content['menu']['projects']['view'] = array(
    '#title' => t('View Projects'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/projects',
  );
  $content['menu']['projects']['add'] = array(
    '#title' => t('Submit new project'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'node/add/om-project',
  );

  //Class Administrators
  $content['menu']['classes'] = array(
    '#title' => t('Manage classes'),
    '#access' => om_admin_menu_role_access(array('Class Administrator')),
    '#href' => 'admin/commerce/products/list',
    '#options' => array(
      'query' => array('sku' => '', 'type' => 'class'),
    ),
  );
  $content['menu']['classes']['add'] = array(
    '#title' => t('Add Class'),
    '#access' => om_admin_menu_role_access(array('Class Administrator')),
    '#href' => 'admin/commerce/products/add/class',
  );
  $content['menu']['classes']['registrations'] = array(
    '#title' => t('Manage registrations'),
    '#access' => om_admin_menu_role_access(array('Class Administrator')),
    '#href' => 'reports/class-registrations',
  );
}

function om_admin_menu_admin_menu_output_alter(&$content) {
  global $user;
  if (!in_array('administrator', $user->roles) && $user->uid != 1) {
    unset($content['menu']['node/add']);
  }
}

function om_admin_menu_role_access($roles) {
  global $user;
  
  foreach($roles as $role) {
    if(in_array($role, $user->roles)) {
      return TRUE;
    } 
  }
  return FALSE;
}

function om_admin_menu_paid_memberships() {
  $paid_memberships = array(
		'Programming Membership',
		'Field Producer Membership', 
		'Editor Membership', 
		'Studio Producer Membership', 
		'Unlimited Membership', 
		'Organizational or Group Membership'
	);

  return $paid_memberships;
}
