<?php


function om_admin_menu_admin_menu_output_build(&$content) {
  $paid_memberships = om_admin_menu_paid_memberships();
  $paid_memberships[] = 'Content Administrator';

  $content['menu']['dashboard'] = array(
    '#title' => t('Dashboard'),
    '#access' => om_admin_menu_role_access(array('authenticated user')),
    '#href' => 'dashboard',
    '#weight' => -50,
	);
  $content['menu']['shows'] = array(
    '#title' => t('Shows'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/shows',
    '#weight' => -20,
  );
  $content['menu']['shows']['view'] = array(
    '#title' => t('View Shows'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/shows',
  );
	$content['menu']['shows']['add'] = array(
    '#title' => t('Submit new show'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'node/add/om-show',
	);
  $content['menu']['projects'] = array(
    '#title' => t('Projects'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/projects',
    '#weight' => '-30',
  );
  $content['menu']['projects']['view'] = array(
    '#title' => t('View Projects'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/projects',
  );
  $content['menu']['projects']['add'] = array(
    '#title' => t('Submit new project'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'node/add/om-project',
  );

  //Government User
  $content['menu']['gov'] = array(
    '#title' => t('Site Configuration'),
    '#access' => om_admin_menu_role_access(array('Gov Administrator')),
    '#href' => 'admin/structure/taxonomy/themes',
    '#weight' => '-40',
  );
  $content['menu']['gov']['themes'] = array(
    '#title' => t('Themes'),
    '#access' => om_admin_menu_role_access(array('Gov Administrator')),
    '#href' => 'admin/structure/taxonomy/themes',
  );
  $content['menu']['gov']['agenda-config'] = array(
    '#title' => t('Archive Page Configuration'),
    '#access' => om_admin_menu_role_access(array('Gov Administrator')),
    '#href' => 'admin/config/om/agenda-manager',
  );

  //Class Administrators
  $content['menu']['classes'] = array(
    '#title' => t('Classes'),
    '#access' => om_admin_menu_role_access(array('Class Administrator')),
    '#href' => 'admin/commerce/products/list',
    '#options' => array(
      'query' => array('sku' => '', 'type' => 'class'),
    ),
  );
  $content['menu']['classes']['add'] = array(
    '#title' => t('Add Class'),
    '#access' => om_admin_menu_role_access(array('Class Administrator')),
    '#href' => 'admin/commerce/products/add/class',
  );
  $content['menu']['classes']['registrations'] = array(
    '#title' => t('Manage registrations'),
    '#access' => om_admin_menu_role_access(array('Class Administrator')),
    '#href' => 'reports/class-registrations',
  );

  //Membership Administrators
  $content['menu']['membership'] = array(
    '#title' => t('Memberships'),
    '#access' => om_admin_menu_role_access(array('Membership Administrator')),
    '#href' => 'reports/members',
  );
  $content['menu']['membership']['report'] = array(
    '#title' => t('Manage Members'),
    '#access' => om_admin_menu_role_access(array('Membership Administrator')),
    '#href' => 'reports/members',
  );
  $content['menu']['membership']['add'] = array(
    '#title' => t('Create Membership Order'),
    '#access' => om_admin_menu_role_access(array('Membership Administrator')),
    '#href' => 'admin/commerce/orders/add',
  );

  //Content Administrators
  $content['menu']['content'] = array(
    '#title' => t('Content'),
    '#access' => om_admin_menu_role_access(array('Content Administrator')),
    '#href' => 'admin/content',
  );
  $content['menu']['content']['add_page'] = array(
    '#title' => t('Add Page'),
    '#access' => om_admin_menu_role_access(array('Content Administrator')),
    '#href' => 'node/add/page',
  );
  $content['menu']['content']['add_form'] = array(
    '#title' => t('Add Form'),
    '#access' => om_admin_menu_role_access(array('Content Administrator')),
    '#href' => 'node/add/webform',
  );
  $content['menu']['content']['add_news'] = array(
    '#title' => t('Add News'),
    '#access' => om_admin_menu_role_access(array('Content Administrator')),
    '#href' => 'node/add/news',
  );
  $content['menu']['content']['navigation'] = array(
    '#title' => t('Edit Menu'),
    '#access' => om_admin_menu_role_access(array('Content Administrator')),
    '#href' => 'admin/structure/menu/manage/main-menu',
  );
  $content['menu']['content']['theme_assets'] = array(
    '#title' => t('Admin Theme Assets'),
    '#access' => om_admin_menu_role_access(array('Content Administrator'), 'om_theme_assets'),
    '#href' => 'om_theme_assets',
  );
  //Reservations Administrators
  $content['menu']['reservations'] = array(
    '#title' => t('Reservations'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'administer_reservations',
  );
  $content['menu']['reservations']['view_reservations'] = array(
    '#title' => t('Manage Reservations'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'administer_reservations',
    '#weight' => -55,
  ); 
  $content['menu']['reservations']['view_products'] = array(
    '#title' => t('View Products'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/commerce/products/list',
    '#options' => array(
      'query' => array('sku' => '', 'type' => 'reservable_product'),
    ),
    '#weight' => -50,
  );
  $content['menu']['reservations']['view_displays'] = array(
    '#title' => t('View Product Displays'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/commerce-displays',
    '#options' => array(
      'query' => array('keys' => '', 'field_crp_category_tid' => 'All', 'type' => 'reservable_product_display'),
    ),
    '#weight' => -47,
  );
  $content['menu']['reservations']['add_product'] = array(
    '#title' => t('Add Product'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/commerce/products/add/reservable-product',
    '#weight' => -45,
  );
  $content['menu']['reservations']['view_product_displays'] = array(
    '#title' => t('Add Product Display'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'node/add/reservable-product-display',
    '#weight' => -40,
  );
  /**
  $content['menu']['reservations']['certifications'] = array(
    '#title' => t('Manage Certifications'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/structure/taxonomy/certifications',
  );**/
  $content['menu']['reservations']['categories'] = array(
    '#title' => t('Manage Categories'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/structure/taxonomy/product_categories',
  );
  $content['menu']['reservations']['locations'] = array(
    '#title' => t('Manage Locations'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/structure/taxonomy/equipment_locations',
  );
  $content['menu']['reservations']['accessories'] = array(
    '#title' => t('Manage Accessories'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/structure/taxonomy/reservable_product_accessories',
  );
  $content['menu']['reservations']['configuration'] = array(
    '#title' => t('Reservations Settings'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/commerce/cr/settings',
  );
  /**
  $content['menu']['reservations']['inventory'] = array(
    '#title' => t('View Current Inventory'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/om/reports/inventory',
  );**/
  $content['menu']['reservations']['global_config'] = array(
    '#title' => t('Admin Global Config'),
    '#access' => om_admin_menu_role_access(array('Reservations Administrator')),
    '#href' => 'admin/commerce/cr/settings',
    '#weight' => 50
   );

  //Schedule Administrators
  $content['menu']['scheduling'] = array(
    '#title' => t('Scheduling Settings'),
    '#access' => om_admin_menu_role_access(array('Schedule Administrator')),
    '#href' => 'om_playback_servers',
  );
  $content['menu']['scheduling']['servers'] = array(
    '#title' => t('Playback Servers'),
    '#access' => om_admin_menu_role_access(array('Schedule Administrator')),
    '#href' => 'om_playback_servers',
  );
  $content['menu']['scheduling']['schedule'] = array(
    '#title' => t('Broadcast Synchronization'),
    '#access' => om_admin_menu_role_access(array('Schedule Administrator')),
    '#href' => 'om_broadcast_schedule',
  );
  $content['menu']['scheduling']['timeslots'] = array(
    '#title' => t('Timeslots'),
    '#access' => om_admin_menu_role_access(array('Schedule Administrator')),
    '#href' => 'om_timeslot_scheduler',
  );
}

function om_admin_menu_admin_menu_output_alter(&$content) {
  global $user;
  if (!in_array('administrator', $user->roles) && $user->uid != 1) {
    unset($content['menu']['node/add']);
    unset($content['menu']['admin/config']);
    unset($content['menu']['admin/commerce']);
    unset($content['menu']['admin/help']);
    unset($content['menu']['admin/index']);
    unset($content['menu']['admin/content']);
    unset($content['menu']['admin/structure']);
  }
}

function om_admin_menu_role_access($roles, $path = false) {
  global $user;
  
  foreach($roles as $role) {
    if(in_array($role, $user->roles)) {
      if (!$path) {
        return TRUE;
      }else{
        if (drupal_valid_path($path)) {
          return TRUE;
        }
      }
    } 
  }
  return FALSE;
}

function om_admin_menu_paid_memberships() {
  $paid_memberships = array(
		'Programming Membership',
		'Field Producer Membership', 
		'Editor Membership', 
		'Studio Producer Membership', 
		'Unlimited Membership', 
    'Organizational or Group Membership',
    'Berkeley Resident',
    'Non-Resident',
    'Student',
    'Lifetime',
    'Berkeley Business or Group',
    'Berkeley Based Non-Profit',
    'Berkeley ASUC Group / Club',
    'Non-Resident Group, Business or Non-Profit',
    'Equipment Access Membership',
    'Equipment and Training Access Membership',
	);

  return $paid_memberships;
}

function om_admin_menu_menu_alter(&$items) {
  // Grant those with "edit terms in [vid]" permission access to list the terms
  // and add new ones, per vocabulary.
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name']['access callback'] = 'taxonomy_term_edit_access';
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name']['access arguments'] = array(3);
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/add']['access callback'] = 'taxonomy_term_edit_access';
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/add']['access arguments'] = array(3);
  $items['devel/switch']['access callback'] = 'om_admin_menu_devel_switch_user_access';
}

/**
 * Ovveride of devel switch access check to make it so users
 * cannot switch to user 1 or administrative users
 */
function om_admin_menu_devel_switch_user_access($name) {
  if (user_access('switch users')) {
    if (drupal_valid_token(@$_GET['token'], "devel/switch/$name|" . @$_GET['destination'], TRUE)) {
      $account = user_load_by_name($name);
      if ($account->uid != 1 && !in_array('administrator', $account->roles)) {
        return true;
      }
    }
  }

  return false;
}
