<?php


function om_admin_menu_admin_menu_output_build(&$content) {
  $paid_memberships = om_admin_menu_paid_memberships();
 
  $content['menu']['dashboard'] = array(
    '#title' => t('Dashboard'),
    '#access' => om_admin_menu_role_access(array('authenticated user')),
    '#href' => 'dashboard',
	);
  $content['menu']['shows'] = array(
    '#title' => t('Manage Shows'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'user/shows',
  );
	$content['menu']['shows']['add'] = array(
    '#title' => t('Submit new show'),
    '#access' => om_admin_menu_role_access($paid_memberships),
    '#href' => 'node/add/om-show',
	);
}

function om_admin_menu_admin_menu_output_alter(&$content) {
  global $user;
  if (!in_array('administrator', $user->roles) && $user->uid != 1) {
    unset($content['menu']['node/add']);
  }
}

function om_admin_menu_role_access($roles) {
  global $user;
  
  foreach($roles as $role) {
    if(in_array($role, $user->roles)) {
      return TRUE;
    } 
  }
  return FALSE;
}

function om_admin_menu_paid_memberships() {
  $paid_memberships = array(
		'Programming Membership',
		'Field Producer Membership', 
		'Editor Membership', 
		'Studio Producer Membership', 
		'Unlimited Membership', 
		'Organizational or Group Membership'
	);

  return $paid_memberships;
}
