<?php

function omf_entityquerydisplay_menu() {
  $items['admin/querydisplay'] = array(
	  'title' => t('Demo Page for entityQueryDisplay Class'),
	  'description' => t('Demo page for entityQueryDisplay Class'),
	  'page callback' => 'omf_entityquerydisplay_demo',
	  'access arguments' => array('access administration pages'),
	  'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

function omf_entityquerydisplay_demo() {
  module_load_include('inc', 'omf_entityquerydisplay', 'includes/entityQueryDisplay');

  $build['table_header'] = array(
    '#markup' => '<h2>entityQueryDisplay Demo</h2>',
  );

  $query = db_select('node')->extend('PagerDefault')->extend('Filter');
  $query->join('users', 'users', 'users.uid = node.uid');
  $query->condition('node.uid', 1)
    ->condition('node.status', 1)
    ->fields('node', array('title', 'nid', 'status', 'created'))
    ->fields('users', array('name'))
    ->limit(10)
    ->filterName('user_name')
    ->orderBy('node.created');
  $result = $query->execute(); 

  $build['filters'] = drupal_get_form('filter_extender_form', $query);

  $header = array(
    array('data' => t('Title')),
    array('data' => t('Nid')),
    array('data' => t('Status')),
    array('data' => t('Created')),
    array('data' => t('Username')),
  );

  $rows = array();
  foreach ($result as $row) {
    $rows[] = array('data' => (array) $row);
  }

  $build['node_table'] = array(
    '#theme' => 'table',
    '#header' => $header,
    '#rows' => $rows,
    '#empty' => t('There was no data found matching your specifications.'),
  );

  $build['pager_pager'] = array('#theme' => 'pager');

  return $build;
}

function omf_entityquerydisplay_filter_elements_user_name() {
  // Regular filters
  $filters = array();
  $filters['name'] = array(
    'title' => t('username'),
    'autocomplete_path' => 'user/autocomplete',
    'field' => 'users.name',
  );

  return $filters;
}

/**
function omf_entityquerydisplay_theme() {
  return array(
    'filter_selection_form' => array(
      'render element' => 'form',
      'file' => 'includes/entityQueryDisplay.inc',
    ),
  );
}**/
