<?php

function omf_entityquerydisplay_menu() {
  $items['admin/querydisplay'] = array(
	  'title' => t('Demo Page for entityQueryDisplay Class'),
	  'description' => t('Demo page for entityQueryDisplay Class'),
	  'page callback' => 'omf_entityquerydisplay_demo',
	  'access arguments' => array('access administration pages'),
	  'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

function omf_entityquerydisplay_demo() {
  $content = '<h2>entityQueryDisplay Demo</h2>';

  $query = db_select('node');
  $query->condition('node.uid', 1)
    ->condition('node.status', 1)
    ->condition('node.created', 1388534400, '>=')
    ->fields('node', array('title', 'nid', 'status', 'created'))
    ->range(0, 25);
  $results = $query->execute(); 

  $content .= '<table>';
  $content .= '<thead><th>Title</th><th>Nid</th><th>Status</th><th>Created</th></thead>';

  foreach ($results as $result) {
    $content .= '<tr>';
    $content .= '<td>'.$result->title.'</td>';
    $content .= '<td>'.$result->nid.'</td>';
    $content .= '<td>'.$result->status.'</td>';
    $content .= '<td>'.$result->created.'</td>';
    $content .= '</tr>';
  }
  $content .= '</table>';

  return $content;
}
