<?php

/**
 * Implements hook_block_info
 */
function om_social_block_info() {
  $blocks = array();
  $blocks['om_social_vertical_sharing'] = array(
    'info' => t('Vertical Social Icons'),
    'cache' => DRUPAL_CACHE_GLOBAL
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function om_social_block_view($delta = "") {
  $blocks = array();
  switch($delta) {
    case 'om_social_vertical_sharing':
      $blocks['content'] = theme('om_social_vertical_sharing');
      break;
  }
  return $blocks;
} 

/**
 * Implements hook_theme
 */
function om_social_theme($existing, $type, $theme, $path) {
  return array(
    'facebook_share' => array(
      'template' => 'facebook_share',
      'path' => $path . '/theme',
      'file' => 'theme.inc',
      'variables' => array('url' => '')
    ),
    'twitter_share' => array(
      'template' => 'twitter_share',
      'path' => $path . '/theme',
      'file' => 'theme.inc',
      'variables' => array('url' => '')
    ),
    'pinterest_share' => array(
      'template' => 'pinterest_share',
      'path' => $path . '/theme',
      'file' => 'theme.inc',
      'variables' => array('image_url' => '')
    ),
    'google_share' => array(
      'template' => 'google_share',
      'path' => $path . '/theme',
      'file' => 'theme.inc',
      'variables' => array('url' => '')
    ),
    'custom_print' => array(
      'function' => 'om_social_custom_print_theme'
    ),
    'om_social_vertical_sharing' => array(
      'path' => $path . '/theme',
      'template' => 'om_social_vertical_sharing',
      'file' => 'theme.inc'
    ),
  );
}

/**
 * Custom theme function to make print icon.
 */

function om_social_custom_print_theme() {
  global $base_path;
  $icon ='<img src="' . $base_path . drupal_get_path('module', 'om_social') . '/theme/images/print-icon.png" />';
  $options = array('html' => TRUE);
  return l($icon, 'print/' . $_GET['q'], $options);
}

function om_social_get_current_path() {
  global $base_url;
  $current_path = $base_url.'/'.request_path();
  return $current_path;
}
