<?php

function om_voting_postmark_init() {
  require_once('sites/all/libraries/postmark/lib/Postmark/Autoloader.php');
}

/**
** Implements hook_menu
**/
function om_voting_menu() {
  $items = array();

  $items['postmark/inbound'] = array(
    'title' => t('Inbound Postmark Messages'),
    'page callback' => 'om_voting_postmark_inbound',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function om_voting_postmark_inbound () {
  //om_voting_postmark_init();
  watchdog('postmark', '<pre>'.print_r($_POST, true).'</pre>');
}
