<?php
/**
 * Implements hook_block_info
 */
function om_theme_assets_block_info() {
  $blocks = array();
  $blocks['om_round_social_media'] = array(
    'info' => t('Round Social Media Icons'), 
    'cache' => DRUPAL_CACHE_GLOBAL
  );
  $blocks['om_site_links'] = array(
    'info' => t('Persistant Site Links'), 
    'cache' => DRUPAL_CACHE_PER_ROLE
  );
  $callout_blocks = om_theme_assets_callout_block_content();
  foreach ($callout_blocks AS $key => $info) {
    $blocks['om_callout_block_' . $key] = array(
      'info' => $info['admin_title'], 
      'cache' => DRUPAL_CACHE_GLOBAL
    );
  }
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function om_theme_assets_block_view($delta = "") {
  $blocks = array();
  switch($delta) {
    case 'om_round_social_media':
      $blocks['content'] = theme('om_round_social_media');
      break;
    case 'om_site_links':
      $blocks['content'] = theme('om_site_links');
      break;
  }
  if (is_numeric(stripos($delta, 'om_callout_block_'))) {
    $index = str_replace('om_callout_block_', '', $delta);
    $callout_blocks = om_theme_assets_callout_block_content();
    $options = array('block_info' => $callout_blocks[$index]);
    $blocks['content'] = theme('om_callout_block', $options);
  }
  return $blocks;
}

/**
 * Implements hook_theme
 */
function om_theme_assets_theme($existing, $type, $theme, $path) {
  return array(
    'om_round_social_media' => array(
      'path' => $path . '/theme',
      'template' => 'om_round_social_media',
      'file' => 'theme.inc'
    ),
    'om_site_links' => array(
      'path' => $path . '/theme',
      'template' => 'om_site_links',
      'file' => 'theme.inc'
    ),
    'om_callout_block' => array(
      'path' => $path . '/theme',
      'template' => 'om_callout_block',
      'file' => 'theme.inc'
    )
  );
}

/**
 * Helper function to return content information for callout blocks.
 *   @todo move Joe's image blocks from om_blocks to this module to replace this.
 */
function om_theme_assets_callout_block_content() {
  $theme_path = drupal_get_path('theme', 'openmedia');
  global $base_path;
  return array(
    0 => array(
      'admin_title' => 'Callout Block 1',
      'block_title' => t('OMP for Public Access and Community Media'),
      'image_path' => $base_path . $theme_path . '/images/callout-1.jpg',
      'url' => 'http://google.com'
    ),
    1 => array(
      'admin_title' => 'Callout Block 2',
      'block_title' => t('OMP for Government'),
      'image_path' => $base_path . $theme_path . '/images/callout-2.png',
      'url' => 'http://google.com'
    ),
    2 => array(
      'admin_title' => 'Callout Block 3',
      'block_title' => t('OMP for Education, Libraries, and CTCs'),
      'image_path' => $base_path . $theme_path . '/images/callout-3.png',
      'url' => 'http://google.com'
    )
  );
}