<?php

function om_theme_assets_block_info() {
  $blocks = array();
  $blocks['om_round_social_media'] = array(
    'info' => t('Round Social Media Icons'), 
    'cache' => DRUPAL_CACHE_GLOBAL
  );
  $blocks['om_site_links'] = array(
    'info' => t('Persistant Site Links'), 
    'cache' => DRUPAL_CACHE_PER_ROLE
  );
  return $blocks;
}

function om_theme_assets_block_view($delta = "") {
  $blocks = array();
  switch($delta) {
    case 'om_round_social_media':
      $blocks['content'] = theme('om_round_social_media');
      break;
    case 'om_site_links':
      $blocks['content'] = theme('om_site_links');
      break;
  }
  return $blocks;
}

function om_theme_assets_theme($existing, $type, $theme, $path) {
  return array(
    'om_round_social_media' => array(
      'path' => $path . '/theme',
      'template' => 'om_round_social_media',
      'file' => 'theme.inc'
    ),
    'om_site_links' => array(
      'path' => $path . '/theme',
      'template' => 'om_site_links',
      'file' => 'theme.inc'
    )
  );
}