<?php

/**
 * Implements hook_permission
 */
function om_field_lock_permission() {
  return array(
    'administer locked fields' => array(
      'title' => t('Administer locked fields'),
      'description' => t('Lock or unlock a field.'),
    ),
  );
}

function om_field_lock_menu() {
  $items = array();
  return $items;
}

//function om_field_lock_entity_query_alter($query) {
  //dsm($query);
  //$query->range['length'] = 0;
  //$field_name = 'field_associated_role';
  //$field = field_read_field($field_name);
  //$field['locked'] = 0; // 0: unlock; 1: lock.
  //field_update_field($field);
//}
