<?php

function ia_js_upload_menu() {
  $items['admin/ia/upload'] = array(
	  'title' => t('Internet Archive Uploader'),
	  'description' => t('Upload to archive.org'),
	  'page callback' => 'ia_js_upload_demo',
	  'access arguments' => array('access administration pages'),
	  'type' => MENU_CALLBACK
  );

  $items['ia/sign'] = array(
    'title' => t('Internet Archive Signature'),
    'page callback' => 'ia_js_upload_sign',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  return $items;
}

function ia_js_upload_demo() {
  drupal_add_js(drupal_get_path('module', 'ia_js_upload', '/includes/evaporate.js'));
  $output = t('This is the demo page.');
  return $output;
}

function ia_js_upload_sign($request) {
  $key = '9Oe9KFJOaJW05MEn';
  $signed_key = base64_encode(hash_hmac('sha256', $request, $key, true));
  print $key;
}
