<?php

function commerce_alters_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'commerce_checkout_form_checkout') {
    global $user;
    $contact_info = profile2_load_by_user($user, 'contact_info');
    $first_name = $contact_info->field_first_name[LANGUAGE_NONE][0]['safe_value'];
    $last_name = $contact_info->field_last_name[LANGUAGE_NONE][0]['safe_value'];
    $full_name = $first_name.' '.$last_name;

    if($first_name && $last_name) {
      $form['customer_profile_billing']['commerce_customer_address'][LANGUAGE_NONE][0]['name_block']['name_line']['#default_value'] = $full_name;
    }
  }
}
